spring:
  docker:
    compose:
      file: /home/kostya-skorik/IdeaProjects/Booking_Service/docker-compose.yaml
      lifecycle-management: start_and_stop
  application:
    name: presentation
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER}
  flyway:
    enabled: true
    # Spring Boot по умолчанию ищет в classpath:db/migration
    # Так как persistence теперь в classpath, он сам найдет папку
    locations: classpath:db/migration
    baseline-on-migrate: true # Полезно для первой инициализации
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: profile,email
  kafka:
    bootstrap-servers: localhost:9092, localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      properties:
        delivery.timeout.ms: 10000
        linger.ms: 1000
        request.timeout.ms: 5000
        max.in.flight.requests.per.connection: 5
        enable:
          idempotence: true

minio:
  ip: http://localhost:9000
  bucket:
    coworking: /coworkings
kafka:
  topic: create_booking_topic

